spring.datasource.url=jdbc:postgresql://localhost:5432/cursos_db
spring.datasource.username=cursos_users
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.expiration=7200000